/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "ErrType.h"
#include "Stm32F103xx.h"

#include "RCC_Private.h"
#include "RCC_Interface.h"

#include "GPIO_prv.h"
#include "GPIO_interface.h"

#include "NVIC_prv.h"
#include "NVIC_interface.h"

#include "SCB_prv.h"
#include "SCB_interface.h"

#include "DMA_prv.h"
#include "DMA_interface.h"

#include "USART_prv.h"
#include "USART_interface.h"


void Notification(void);
void Notification_1(void);

uint8_t Src_Array[10] = {0};
char Src_Array2[40] = {" DMA Tx and Rx work well ,Great work "};

PinConfig_t Local_LEDConfig={
		.Port = PORTC,
		.PinNum = PIN13,
		.Mode = OUTPUT_MODE2MHZ,
		.OutputConf = GP_OUTPUT_PP,
		.InputConf = FLOATING_INPUT
};
PinConfig_t Local_LEDConfig_2={
		.Port = PORTC,
		.PinNum = PIN14,
		.Mode = OUTPUT_MODE2MHZ,
		.OutputConf = GP_OUTPUT_PP,
		.InputConf = FLOATING_INPUT
};

PinConfig_t Local_TxConfig={
		.Port = PORTA,
		.PinNum = PIN2,
		.Mode = OUTPUT_MODE10MHZ,
		.OutputConf = AF_OUTPUT_PP,
		.InputConf = FLOATING_INPUT
};
PinConfig_t Local_RxConfig={
		.Port = PORTA,
		.PinNum = PIN3,
		.Mode = INPUT_MODE,
		.OutputConf = OUTPUT_MODE2MHZ,
		.InputConf = FLOATING_INPUT
};
USART_ConfigReg_t Local_USART2Tx={
		.USART_BAUDRATE = 115200,
		.USART_HWFLOWCONTROL = USART_HW_FLOW_CONTROL_OFF,
		.USART_MODE = USART_RXTX,
		.USART_PARITYBIT = PARITY_CONTROL_DISABLE,
		.USART_STOPBITS = _1_STOP_BIT,
		.USART_SYNCHMODE = CLOCK_DISABLE,
		.USART_USARTNUMBER = USART_NUM2,
		.USART_WORDLENGTH = _8_DATA_BITS
};
const DMA_Interrupt_t DMA1_Int = {
			.DMA_INTERRUPT_TCIE = DMA_INT_TCIE_ENABLED ,
			.DMA_INTERRUPT_TEIE = DMA_INT_TEIE_ENABLED ,
			.DMA_INTERRUPT_THIE = DMA_INT_THIE_ENABLED ,
	};

	DMA_InitConfig_t DMA1_Init = {

			.DMA_NUMBER = DMA_NUM_1,
			.DMA_CHANNEL_NUMBER = DMA_CHANNEL_7,
			.DMA_CIRCULAR_MODE = DMA_CIRCULAR_DISABLED,
			.DMA_DATA_TRANS_DIR = DMA_DIR_M2P,
			.DMA_INT_EN_STATE = DMA_INTERRUPT_ENABLED,
			.DMA_INTs_STATE = DMA1_Int,
			.DMA_MEM_INC = DMA_MINC_ENABLE,
			.DMA_PERIPH_INC = DMA_PINC_DISABLE,
			.DMA_PERIPH_SIZE = DMA_8_BITS_PSIZE,
			.DMA_MEM_SIZE = DMA_8_BITS_MSIZE,
			.DMA_PRIORITY = DMA_PRIORITY_HIGH

	};
	const DMA_Interrupt_t DMA1_Int2 = {
				.DMA_INTERRUPT_TCIE = DMA_INT_TCIE_ENABLED ,
				.DMA_INTERRUPT_TEIE = DMA_INT_TEIE_ENABLED ,
				.DMA_INTERRUPT_THIE = DMA_INT_THIE_ENABLED ,
		};

		DMA_InitConfig_t DMA1_Init2 = {

				.DMA_NUMBER = DMA_NUM_1,
				.DMA_CHANNEL_NUMBER = DMA_CHANNEL_6,
				.DMA_CIRCULAR_MODE = DMA_CIRCULAR_DISABLED,
				.DMA_DATA_TRANS_DIR = DMA_DIR_P2M,
				.DMA_INT_EN_STATE = DMA_INTERRUPT_ENABLED,
				.DMA_INTs_STATE = DMA1_Int2,
				.DMA_MEM_INC = DMA_MINC_ENABLE,
				.DMA_PERIPH_INC = DMA_PINC_DISABLE,
				.DMA_PERIPH_SIZE = DMA_8_BITS_PSIZE,
				.DMA_MEM_SIZE = DMA_8_BITS_MSIZE,
				.DMA_PRIORITY = DMA_PRIORITY_HIGH

		};

int main(void)
{

	RCC_SetClkSts(CLK_SRC_HSE,RCC_ON);
	RCC_SetSysClk(CLK_SRC_HSE);
	/*Enable APB1 for USART2*/
	RCC_AHBEnableClock(AHB_DMA1);
	RCC_APB1EnableClock(APB1_USART2);
	RCC_APB2EnableClock(APB2_IOPA);
	RCC_APB2EnableClock(APB2_IOPC);

	SCB_SetPriorityGroup(_4G_4SG);
	NVIC_SetIRQnPriority(NVIC_IRQ_DMA1_Channel7, 0b0000);
	NVIC_EnableIRQ(NVIC_IRQ_DMA1_Channel7);
	NVIC_SetIRQnPriority(NVIC_IRQ_DMA1_Channel6, 0b0000);
	NVIC_EnableIRQ(NVIC_IRQ_DMA1_Channel6);

	GPIO_u8PinInit(&Local_LEDConfig);
	GPIO_u8PinInit(&Local_LEDConfig_2);
	GPIO_u8PinInit(&Local_TxConfig);
	GPIO_u8PinInit(&Local_RxConfig);
	DMA_SetCallBack(DMA_NUM_1, DMA_CHANNEL_7, DMA_CHANNELx_TRANSFER_COMPLETE_FLAG, Notification);
	DMA_SetCallBack(DMA_NUM_1, DMA_CHANNEL_6, DMA_CHANNELx_TRANSFER_COMPLETE_FLAG, Notification_1);

	DMA_Init(&DMA1_Init);
	DMA_Init(&DMA1_Init2);
	USART_Init(&Local_USART2Tx);

	USART_ReceiveDataEnable_DMA(&Local_USART2Tx);
	DMA_Start_IT(&DMA1_Init2, (uint32_t)(&USART2->USART_DR),(uint32_t)Src_Array , 10);

	GPIO_u8SetPinValue(PORTC, PIN13, PIN_HIGH);
	GPIO_u8SetPinValue(PORTC, PIN14, PIN_HIGH);
	while(1)
	{



	}
}

void Notification(void)
{

	GPIO_u8SetPinValue(PORTC, PIN13, PIN_LOW);
}
void Notification_1(void)
{
	USART_TransmitDataEnable_DMA(&Local_USART2Tx);
	DMA_Start_IT(&DMA1_Init, (uint32_t)Src_Array2 , (uint32_t)(&USART2->USART_DR) , 40);
	GPIO_u8SetPinValue(PORTC, PIN14, PIN_LOW);
}
