/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "ErrType.h"
#include "Stm32F103xx.h"

#include "RCC_Private.h"
#include "RCC_Interface.h"

#include "GPIO_prv.h"
#include "GPIO_interface.h"

#include "NVIC_prv.h"
#include "NVIC_interface.h"

#include "SCB_prv.h"
#include "SCB_interface.h"

#include "DMA_prv.h"
#include "DMA_interface.h"

void Notification_DMA(void);

int main(void)
{
	uint8_t G_SrcArray[10] = { 1 , 2, 3, 4, 5, 6, 7, 8 , 9, 10};
	uint8_t G_DstArray[10] = {0};
	/*SET HSE ON*/
	RCC_SetClkSts(CLK_SRC_HSE, RCC_ON);
	/*SET HSE SYSTEM CLOCK*/
	RCC_SetSysClk(CLK_SRC_HSE);

	/*Enable RCC Clock line for DMA1*/
	RCC_AHBEnableClock(AHB_DMA1);

	RCC_APB2EnableClock(APB2_IOPA);

	SCB_SetPriorityGroup(_4G_4SG);

	NVIC_SetIRQnPriority(NVIC_IRQ_DMA1_Channel1, 0b0001);


	NVIC_EnableIRQ(NVIC_IRQ_DMA1_Channel1);

	PinConfig_t Led1 ={
			.Port = PORTA,
			.PinNum = PIN1,
			.Mode = OUTPUT_MODE2MHZ,
			.InputConf = INPUT_PUPD,
			.OutputConf = GP_OUTPUT_PP
	};

	/*DMA1 Configuration STRUCT*/

	DMA_Interrupt_t DMA1_Int = {
			.DMA_INTERRUPT_TCIE = DMA_INT_TCIE_ENABLED ,
			.DMA_INTERRUPT_TEIE = DMA_INT_TEIE_DISABLED ,
			.DMA_INTERRUPT_THIE = DMA_INT_THIE_DISABLED ,
	};

	DMA_InitConfig_t DMA1_Init = {

			.DMA_NUMBER = DMA_NUM_1,
			.DMA_CHANNEL_NUMBER = DMA_CHANNEL_1,
			.DMA_CIRCULAR_MODE = DMA_CIRCULAR_DISABLED,
			.DMA_DATA_TRANS_DIR = DMA_DIR_M2M,
			.DMA_INT_EN_STATE = DMA_INTERRUPT_ENABLED,
			.DMA_INTs_STATE = DMA1_Int,
			.DMA_MEM_INC = DMA_MINC_ENABLE,
			.DMA_PERIPH_INC = DMA_PINC_ENABLE,
			.DMA_PERIPH_SIZE = DMA_8_BITS_PSIZE,
			.DMA_MEM_SIZE = DMA_8_BITS_MSIZE,
			.DMA_PRIORITY = DMA_PRIORITY_VERY_HIGH

	};

	GPIO_u8PinInit(&Led1);
	/*DMA Initialization*/
	DMA_Init(&DMA1_Init);
	DMA_SetCallBack(DMA_NUM_1, DMA_CHANNEL_1, DMA_CHANNELx_TRANSFER_COMPLETE_FLAG, Notification_DMA);
	//DMA_InterruptEnable(&DMA1_Init);
	DMA_Start_IT(&DMA1_Init, &G_SrcArray[0] , &G_DstArray[0] , 10 );


	while(1)
	{

	}
}


void Notification_DMA(void)
{
	GPIO_u8SetPinValue(PORTA, PIN1, PIN_HIGH);
}


